name: heroku_deploy

on:
  push:
    branches:
      - main

jobs:                        
  build:                          
    runs-on: ubuntu-latest                        
    steps:
     - uses: actions/checkout@v2        
     - uses: akhileshns/heroku-deploy@v3.6.8
       with: 
         heroku_api_key: "caff7460-29c4-4f52-af0b-0aa15ee40ebf"
         heroku_app_name: "salty-shore-37417"                                 
         heroku_email: "jdavid.macer@gmail.com"                                  
         healthcheck: "https://salty-shore-37417.herokuapp.com/"                                     
   
         usedocker: true                                  
         delay: 60                                 
         rollbackonhealthcheckfailed: true
env: 
  HD_API_KEY: ${{secrets.MAPS_API_KEY}} # Docker env var
